/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Channel implements Serializable {

    private static final long serialVersionUID = -530348596;

    private final Integer channelId;
    private final String  name;
    private final String  description;
    private final String  rules;

    public Channel(Channel value) {
        this.channelId = value.channelId;
        this.name = value.name;
        this.description = value.description;
        this.rules = value.rules;
    }

    public Channel(
        Integer channelId,
        String  name,
        String  description,
        String  rules
    ) {
        this.channelId = channelId;
        this.name = name;
        this.description = description;
        this.rules = rules;
    }

    public Integer getChannelId() {
        return this.channelId;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }

    public String getRules() {
        return this.rules;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Channel (");

        sb.append(channelId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(rules);

        sb.append(")");
        return sb.toString();
    }
}
