/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Image implements Serializable {

    private static final long serialVersionUID = 1008649827;

    private final Integer imageId;
    private final String  directory;
    private final String  fileName;

    public Image(Image value) {
        this.imageId = value.imageId;
        this.directory = value.directory;
        this.fileName = value.fileName;
    }

    public Image(
        Integer imageId,
        String  directory,
        String  fileName
    ) {
        this.imageId = imageId;
        this.directory = directory;
        this.fileName = fileName;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public String getDirectory() {
        return this.directory;
    }

    public String getFileName() {
        return this.fileName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Image (");

        sb.append(imageId);
        sb.append(", ").append(directory);
        sb.append(", ").append(fileName);

        sb.append(")");
        return sb.toString();
    }
}
