/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 1673749597;

    private final Integer   postId;
    private final String    message;
    private final Timestamp dateTime;
    private final Integer   threadId;
    private final Integer   imageId;

    public Post(Post value) {
        this.postId = value.postId;
        this.message = value.message;
        this.dateTime = value.dateTime;
        this.threadId = value.threadId;
        this.imageId = value.imageId;
    }

    public Post(
        Integer   postId,
        String    message,
        Timestamp dateTime,
        Integer   threadId,
        Integer   imageId
    ) {
        this.postId = postId;
        this.message = message;
        this.dateTime = dateTime;
        this.threadId = threadId;
        this.imageId = imageId;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public String getMessage() {
        return this.message;
    }

    public Timestamp getDateTime() {
        return this.dateTime;
    }

    public Integer getThreadId() {
        return this.threadId;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(postId);
        sb.append(", ").append(message);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(threadId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
