/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Token implements Serializable {

    private static final long serialVersionUID = 970130812;

    private final Integer tokenId;
    private final String  token;
    private final Date    expiryDate;
    private final Integer userId;

    public Token(Token value) {
        this.tokenId = value.tokenId;
        this.token = value.token;
        this.expiryDate = value.expiryDate;
        this.userId = value.userId;
    }

    public Token(
        Integer tokenId,
        String  token,
        Date    expiryDate,
        Integer userId
    ) {
        this.tokenId = tokenId;
        this.token = token;
        this.expiryDate = expiryDate;
        this.userId = userId;
    }

    public Integer getTokenId() {
        return this.tokenId;
    }

    public String getToken() {
        return this.token;
    }

    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public Integer getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Token (");

        sb.append(tokenId);
        sb.append(", ").append(token);
        sb.append(", ").append(expiryDate);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
