/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 872138981;

    private final Integer id;
    private final String  name;
    private final String  email;
    private final String  passwordHash;
    private final String  passwordSalt;
    private final Boolean enabled;

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.passwordHash = value.passwordHash;
        this.passwordSalt = value.passwordSalt;
        this.enabled = value.enabled;
    }

    public Users(
        Integer id,
        String  name,
        String  email,
        String  passwordHash,
        String  passwordSalt,
        Boolean enabled
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
        this.passwordSalt = passwordSalt;
        this.enabled = enabled;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getEmail() {
        return this.email;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public String getPasswordSalt() {
        return this.passwordSalt;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(passwordSalt);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
