/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles implements Serializable {

    private static final long serialVersionUID = -948933849;

    private final Integer userId;
    private final String  role;

    public UserRoles(UserRoles value) {
        this.userId = value.userId;
        this.role = value.role;
    }

    public UserRoles(
        Integer userId,
        String  role
    ) {
        this.userId = userId;
        this.role = role;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public String getRole() {
        return this.role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoles (");

        sb.append(userId);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
