/*
 * This file is generated by jOOQ.
*/
package ru.rem.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rem.db.tables.Thread;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThreadRecord extends UpdatableRecordImpl<ThreadRecord> implements Record6<Integer, String, Integer, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = -150258195;

    /**
     * Setter for <code>public.thread.thread_id</code>.
     */
    public ThreadRecord setThreadId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.thread_id</code>.
     */
    public Integer getThreadId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.thread.message</code>.
     */
    public ThreadRecord setMessage(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.thread.priority</code>.
     */
    public ThreadRecord setPriority(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.thread.date_time</code>.
     */
    public ThreadRecord setDateTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.date_time</code>.
     */
    public Timestamp getDateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.thread.channel_id</code>.
     */
    public ThreadRecord setChannelId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.channel_id</code>.
     */
    public Integer getChannelId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.thread.image_id</code>.
     */
    public ThreadRecord setImageId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.thread.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Thread.THREAD.THREAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Thread.THREAD.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Thread.THREAD.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Thread.THREAD.DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Thread.THREAD.CHANNEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Thread.THREAD.IMAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getChannelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value1(Integer value) {
        setThreadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value2(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value3(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value4(Timestamp value) {
        setDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value5(Integer value) {
        setChannelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord value6(Integer value) {
        setImageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThreadRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThreadRecord
     */
    public ThreadRecord() {
        super(Thread.THREAD);
    }

    /**
     * Create a detached, initialised ThreadRecord
     */
    public ThreadRecord(Integer threadId, String message, Integer priority, Timestamp dateTime, Integer channelId, Integer imageId) {
        super(Thread.THREAD);

        set(0, threadId);
        set(1, message);
        set(2, priority);
        set(3, dateTime);
        set(4, channelId);
        set(5, imageId);
    }
}
