/*
 * This file is generated by jOOQ.
*/
package ru.rem.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.rem.db.tables.Channel;
import ru.rem.db.tables.Databasechangelog;
import ru.rem.db.tables.Databasechangeloglock;
import ru.rem.db.tables.Image;
import ru.rem.db.tables.Post;
import ru.rem.db.tables.Thread;
import ru.rem.db.tables.Token;
import ru.rem.db.tables.UserRoles;
import ru.rem.db.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1595060607;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.channel</code>.
     */
    public final Channel CHANNEL = ru.rem.db.tables.Channel.CHANNEL;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = ru.rem.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = ru.rem.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.image</code>.
     */
    public final Image IMAGE = ru.rem.db.tables.Image.IMAGE;

    /**
     * The table <code>public.post</code>.
     */
    public final Post POST = ru.rem.db.tables.Post.POST;

    /**
     * The table <code>public.thread</code>.
     */
    public final Thread THREAD = ru.rem.db.tables.Thread.THREAD;

    /**
     * The table <code>public.token</code>.
     */
    public final Token TOKEN = ru.rem.db.tables.Token.TOKEN;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = ru.rem.db.tables.UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = ru.rem.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CHANNEL_CHANNEL_ID_SEQ,
            Sequences.IMAGE_IMAGE_ID_SEQ,
            Sequences.POST_POST_ID_SEQ,
            Sequences.THREAD_PRIORITY_SEQ,
            Sequences.THREAD_THREAD_ID_SEQ,
            Sequences.TOKEN_TOKEN_ID_SEQ,
            Sequences.USER_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Channel.CHANNEL,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Image.IMAGE,
            Post.POST,
            Thread.THREAD,
            Token.TOKEN,
            UserRoles.USER_ROLES,
            Users.USERS);
    }
}
