/*
 * This file is generated by jOOQ.
*/
package ru.rem.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.channel_channel_id_seq</code>
     */
    public static final Sequence<Long> CHANNEL_CHANNEL_ID_SEQ = new SequenceImpl<Long>("channel_channel_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.image_image_id_seq</code>
     */
    public static final Sequence<Long> IMAGE_IMAGE_ID_SEQ = new SequenceImpl<Long>("image_image_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.post_post_id_seq</code>
     */
    public static final Sequence<Long> POST_POST_ID_SEQ = new SequenceImpl<Long>("post_post_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.thread_priority_seq</code>
     */
    public static final Sequence<Long> THREAD_PRIORITY_SEQ = new SequenceImpl<Long>("thread_priority_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.thread_thread_id_seq</code>
     */
    public static final Sequence<Long> THREAD_THREAD_ID_SEQ = new SequenceImpl<Long>("thread_thread_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.token_token_id_seq</code>
     */
    public static final Sequence<Long> TOKEN_TOKEN_ID_SEQ = new SequenceImpl<Long>("token_token_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_seq</code>
     */
    public static final Sequence<Long> USER_SEQ = new SequenceImpl<Long>("user_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
