/*
 * This file is generated by jOOQ.
*/
package ru.rem.db;


import javax.annotation.Generated;

import ru.rem.db.tables.Channel;
import ru.rem.db.tables.Databasechangelog;
import ru.rem.db.tables.Databasechangeloglock;
import ru.rem.db.tables.Image;
import ru.rem.db.tables.Post;
import ru.rem.db.tables.Thread;
import ru.rem.db.tables.Token;
import ru.rem.db.tables.UserRoles;
import ru.rem.db.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.channel</code>.
     */
    public static final Channel CHANNEL = ru.rem.db.tables.Channel.CHANNEL;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = ru.rem.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = ru.rem.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.image</code>.
     */
    public static final Image IMAGE = ru.rem.db.tables.Image.IMAGE;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST = ru.rem.db.tables.Post.POST;

    /**
     * The table <code>public.thread</code>.
     */
    public static final Thread THREAD = ru.rem.db.tables.Thread.THREAD;

    /**
     * The table <code>public.token</code>.
     */
    public static final Token TOKEN = ru.rem.db.tables.Token.TOKEN;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = ru.rem.db.tables.UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = ru.rem.db.tables.Users.USERS;
}
